### ISSUE TITLE
First call to either api or getAccessCode throws a NullReferenceException

### ISSUE THREAD

**Issue by sameerfairgoogl** [barans/FacebookCsharpSdk#1]
When the Connect request is initialized whilst either api() or getAccessCode() is called, the first time a NullReferenceException is thrown, but the second time api() or getAccessCode() are called, execution seem to continue without a hitch

**Comment by sameerfairgoogl** [comment]
Just left a pull request for it. Was just a flow issue. Please have a look

**Comment by barans** [comment]
merged the code. thanks a lot :)
